### ISSUE TITLE
question about progress

### ISSUE THREAD

**Issue by xivk** [KelsonBall/Roslyn.Lua#1]
Just wanted to ping you and ask if this project is still alive? And if not how far along is it? Looking at the code there is more in dev...

I'm extremely interested in this because I have performance issues related to lua being interpreted in [Itinero](https://github.com/itinero/routing).

Any info you can give or any points on alternative implementation or how to proceed are welcome!

**Comment by KelsonBall** [comment]
Hi, thanks for your interest! Currently I'd describe regolith as an "ongoing early stage research project" that my day job has taken more attention from than I'd like 😁

As a "transpiled" language it does have the potential to beat interpreter approached in performance, but to me performance is a secondary priority after making a first class educational language for students with an intuitive type system and first class debugging tools.

Currently, with how much time I have to put into the project as the sole contributor, and how early in development it is, it'll be about a year until regolith code is usefully runnable in a .net environment

*Compared to other interpreted languages* the C lua interpreter alreadt provides good performance characterstics, and there may be .net bindings to LuaJIT, which iirc is the current highest performance option for running Lua.

**Comment by xivk** [comment]
Thanks for your answer, I'll keep an eye on this project.
